### ISSUE TITLE
How i install this?

### ISSUE THREAD

**Issue by Jorapama** [djpadbit/Sound-Physics#20]
I searched tutorial followed them and I can not make this mod work, I installed the forge, put the **Sound-Physics-Mod-1.12.2.jar** in the **Mods folder** put the **Sound-Physics-Soundfix-Resource-Pack.zip** in the **resouce pack folder**, and does not work! Can someone help me?

**Comment by djpadbit** [comment]
The resourcepack is not needed anymore if you're using my fork since there is an automatic stereo to mono downmixing of sounds. Are you sure you downloaded the right jar file though ? The latest one would be this one https://github.com/djpadbit/Sound-Physics/releases/download/1.0.8/Sound-Physics-1.12.2.jar.
