### ISSUE TITLE
Sound issues when moving around

### ISSUE THREAD

**Issue by MineyShadow** [djpadbit/Sound-Physics#24]
Forge : 14.23.5.2847
Minecraft version: 1.12.2
Mods:
- DynamicSurroundings-1.12.2-3.6.0.2
- OreLib-1.12.2-3.6.0.1
- preview_OptiFine_1.12.2_HD_U_F6_pre1
- Sound-Physics-1.12.2 (1.0.8 Patch 1)

When moving around (usually at high speeds/flying) various sounds will stutter, i notice this mostly around beach biomes with the dynamic surroundings sound effects, maybe it affects other sounds as well, this does not happen when sound physics mod is not installed. When i used the older version of the mod (daipenger's sound physics) this issue happens with it as well.

**Comment by djpadbit** [comment]
I'm not sure we are talking about the same thing but i'm aware of an issue similar and it's due to Dynamic Surroundings. The tracking audio sources it uses don't follow fast enough the player so when moving at high speeds the sounds will be lagging behind. Which is why it sounds like it's stuttering. It doesn't sound as bad without Sound Physics because the sounds aren't on the player but over them to do some attenuation. I don't know if is the issue you are talking about thought.

**Comment by MineyShadow** [comment]
Yeah, that sounds like the issue I described above.

**Comment by djpadbit** [comment]
Then i can't do much about it, sorry. It's a Dynamic Surroundings problem. I'll close this issue.
