### ISSUE TITLE
The betweenlands mod rift sounds

### ISSUE THREAD

**Issue by MineyShadow** [djpadbit/Sound-Physics#25]
Forge : 14.23.5.2847
Minecraft version: 1.12.2
Mods:
- Sound-Physics-1.12.2 (1.0.8 Patch 1)
- TheBetweenlands-3.5.7

The rift in the sky does not make its opening sounds with sound physics installed, This issue does not happen in daipenger's sound physics. (You can test the rift with /blevent toggle thebetweenlands:rift while in the dimension)

**Comment by djpadbit** [comment]
Thanks for the bug report, if you find anymore sounds that don't play correctly please report them. It should be fixed in https://github.com/djpadbit/Sound-Physics/commit/8ba9172250ffd3f7e8ce587f13af19fdf0cc27de. In the meantime you can use this build with the fix [Sound-Physics-1.12.2.zip](https://github.com/djpadbit/Sound-Physics/files/4300454/Sound-Physics-1.12.2.zip).
