### ISSUE TITLE
No reverb when used with OpenAL's HRTF processing

### ISSUE THREAD

**Issue by Kaiten10** [djpadbit/Sound-Physics#32]
I updated OpenAL to 1.20.1 and enabled HRTF processing (full directional audio). The directional audio works great and the sound damping from this mod as well. The only thing missing was the reverb. I get this error message in the log:

[12:26:51] [Thread-5/ERROR] [soundphysics]: Error while setting environment for source: 104 OpenAL error AL_INVALID_VALUE

This line is repeated for every sound. The same thing happens when I tried it on OpenAL 1.18.2, it seems enabling HRTF processing is causing the issue. It's still playable but it would be amazing to have full directional audio working with reverb as well!

Instructions to enable HRTF processing can be found here:
https://www.reddit.com/r/oculus/comments/1fzonq/psa_for_games_using_openal_including_minecraft/

Demo with HRTF on: https://youtu.be/AN77W6rLv-Q
HRTF off: https://youtu.be/sT1NFY0q80Y

**Comment by djpadbit** [comment]
In openal 1.18 and up, the ammount of maximum aux send is now 16 but the default went from 4 to 2 (Sound Physics needs 4) and you have to request more send filters when creating the openal context. Only 2 of the reverb effects get applied to the source. That's why it spews out errors. I'm only guessing here though. Because i had a similar problem when porting to 1.15.2. You should still hear at lest a bit of reverb ?

**Comment by Kaiten10** [comment]
At least from my testing, 1.18 and above has noticeable loss of reverb when HRTF is turned on, as if it isn't there. But thanks to your point about 1.18 and up, I tried it with 1.17.2 and everything seems to be working, thanks!

**Comment by djpadbit** [comment]
Good to hear, I'll close the issue then.
