### ISSUE TITLE
Sound Physics breaks The Midnight dimension echo.

### ISSUE THREAD

**Issue by Artgeologist** [djpadbit/Sound-Physics#36]
When loading Sound Physics with The Midnight mod, the echo/reverberations in the midnight dimension no longer work.

**Comment by djpadbit** [comment]
Yes that's an intentional patch because the midnight uses effects which are incompatible with Sound Physics, as stated in https://github.com/djpadbit/Sound-Physics/issues/27. And i didn't bother to readd the reverb because i didn't have a solution that i liked. But since i got another issue about it, i figured i might aswell add it. It's still not great but it works. [Here](https://github.com/djpadbit/Sound-Physics/files/4928014/Sound-Physics-1.12.2-1.0.9.zip)'s a build with the fix.
