### ISSUE TITLE
dirt breaking sound is too loud

### ISSUE THREAD

**Issue by Oaklizard-2047** [djpadbit/Sound-Physics#38]
it seems like the dirt breaking sound is too loud when its in front of me. i can turn down the volume, but then explosions is going to be muffled even a few blocks away. i have dynamic surrounding installed. so how do i fix this?

**Comment by djpadbit** [comment]
I don't quite understand, Sound Physics changes the sound attenuation to be rolloff rather than linear to be more realistic. It also multiplies all affected sounds's volume by the global volume multiplier that you can configure in the settings (default is 4) to compensate that. I think it's working as intended ?

**Comment by Oaklizard-2047** [comment]
so it is normal that its loud?

**Comment by djpadbit** [comment]
I'm fairly certain it is.
