### ISSUE TITLE
"Affect Note Blocks" Inneffective (1.12.2, 1.0.9)

### ISSUE THREAD

**Issue by BleedingOptimism** [djpadbit/Sound-Physics#41]
The volume of notes is scaled based on distance (and stuff) whether this option is on or off, which I'm guessing is a bug! (Maybe I misunderstand what the option is supposed to do?)

If you need more information, please let me know. I just tested with no mods except for Sound Physics and it's the same result. Am I missing something obvious? Using Forge 14.23.5.2847 (the last version before structure change, because I'm using the Technic Launcher).

**Comment by djpadbit** [comment]
What option specifically are you talking about ?

**Comment by BleedingOptimism** [comment]
Hi, it's the "Affect Note Blocks" option:

general {
    # If true, note blocks will be processed. [default: true]
    B:"Affect Note Blocks"=false

**Comment by djpadbit** [comment]
The volume distance function changes are global (at least for all sounds that go through paulscode sound system). It's now rolloff rather than linear. This config option only changes if the note blocks are processed by Sound Physics itself. So if it's turned on, the note blocks will have reverb and be muffled when behind blocks otherwise they won't.

**Comment by BleedingOptimism** [comment]
Ah okay. Thank you very much for putting up with me knowing nothing about the sound system!
