### ISSUE TITLE
Crash with RotN Modpack

### ISSUE THREAD

**Issue by CalaMariGold** [djpadbit/Sound-Physics#42]
https://pastebin.com/dU4prBH1

**Comment by CalaMariGold** [comment]
Fixed by starting a new world that hasn't used Sound Filters in the past.

**Comment by CalaMariGold** [comment]
Just kidding, still persists even on new worlds.

**Comment by djpadbit** [comment]
It should be fixed in master, [here](https://github.com/djpadbit/Sound-Physics/files/5177244/Sound-Physics-1.12.2-1.0.9.zip)'s a build. But it's a pretty weird issue, could i have the full log ? i'd like to see if something bad happened at the init for it to not have a reference to the minecraft instance.

**Comment by CalaMariGold** [comment]
I'll paste it once it pops up again. Its pretty uncommon it seems. I've been on the latest build.

**Comment by CalaMariGold** [comment]
Could you upload a release of that build on GH so we could use it in our modpack via Mod Director?

**Comment by djpadbit** [comment]
It was a good time to make a release anyways so i went ahead and made one. You can find it [here](https://github.com/djpadbit/Sound-Physics/releases/tag/1.0.10).
