### ISSUE TITLE
Elytra Crash [1.12]

### ISSUE THREAD

**Issue by DarianLStephens** [djpadbit/Sound-Physics#44]
I can't be 100% certain, but it seems this mod is causing a crash after you use the Elytra too many times, or perhaps just at random?
You also seem to lack the Elytra sound, but perhaps that's due to interference from another mod?

Investigating this crash online, Sound Physics has been the sole mod shared between each report, and so appears to be the most likely cause.

No crash report, unfortunately, as the world simply hangs and saves, then never responds again, forcing me to kill the process (I've left the game running for 5+ minutes after it hanged, and it never recovered).

Apologies if this ends up being a false-positive, but I'm not sure where else to look.

**Comment by djpadbit** [comment]
Sound Physics doesn't handle moving sounds yet so it's normal that the elytra sound isn't processed.
For the hanging, I managed to recreate the problem very easily actually which is quite the problem. From what i'm seeing, it's a deadlock between the chunk renderer threads and the sound system thread (where Sound Physics's on play sound hook is run). They are both stuck on the player's EntityDataManager's read lock inside getEyeHeight because that function checks if the player is in a elytra which is a value stored inside the data manager. But it shouldn't deadlock as they all want to read and not write and a ReentrantReadWriteLock should let them all read fine. This is probably gonna take a bit of time to figure out so i'll try to keep this updated as i'm working on it.

**Comment by djpadbit** [comment]
It should be fixed now. Since it's a pretty important bug, i made a patch release that you can download [here](https://github.com/djpadbit/Sound-Physics/releases/tag/1.0.10-1).
